version: "3.8"
services:

  cliente-estandar:
    tty: true
    build:
      context: ./cliente-estandar
    container_name: cliente-estandar
    ports:
      - 8081:8081
    environment:  
      - DOCKER_CONTAINER_EXECUTION=true
      - PORT=8081
      - REQUEST_HANDLING_MICROSERVICE_HOST=127.0.0.1
      - REQUEST_HANDLING_MICROSERVICE_PORT=9001
    depends_on:  
      - microservicio-gestion-peticiones 

  cliente-admin:
    tty: true
    build:
      context: ./cliente-admin
    container_name: cliente-admin
    ports:
      - 8080:8080
    environment:  
      - DOCKER_CONTAINER_EXECUTION=true
      - PORT=8080
      - ADMINISTRATION_MICROSERVICE_HOST=127.0.0.1
      - ADMINISTRATION_MICROSERVICE_PORT=9000
      - REFRESH_PERIOD_MS=1000
      - MAX_CARDS_PER_CONTAINER=10000
      - ALLOWED_IPS=0.0.0.0,:1
    depends_on:  
      - microservicio-administracion 

  microservicio-administracion:
    tty: true
    build:
      context: ./microservicio-administracion
    container_name: microservicio-administracion
    ports:
      - 9000:9000
    environment: 
      - DOCKER_CONTAINER_EXECUTION=true 
      - MONGODB_CONNECTION_STRING=${ADMINISTRATION_MICROSERVICE_MONGODB_CONNECTION_STRING}
      - PORT=9000
      - RENDER_SERVER_PORT=3000
      - REQUEST_HANDLING_MICROSERVICE_HOST=microservicio-gestion-peticiones
      - REQUEST_HANDLING_MICROSERVICE_PORT=9001
      - ALLOWED_IPS=0.0.0.0,:1

  microservicio-gestion-peticiones:
    tty: true
    build:
      context: ./microservicio-gestion-peticiones
    container_name: microservicio-gestion-peticiones
    ports:
      - 9001:9001
    environment:  
      - DOCKER_CONTAINER_EXECUTION=true
      - MONGODB_CONNECTION_STRING=${REQUEST_HANDLING_MICROSERVICE_MONGODB_CONNECTION_STRING}
      - PORT=9001
      - RENDER_SERVER_PORT=3000
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - DB_CHECK_PERIOD_MS=30000
      - CLEANUP_INTERVAL_MS=100000
      - EMAIL_SENDING_BACKUP_INTERVAL_MS=25000
      - RENDERING_SERVER_POLLING_INTERVAL_MS=1000
      - MAX_FILE_SIZE_BYTES=1073741824

  servidor-renderizado:
    tty: true
    build:
      context: ./servidor-renderizado
    container_name: servidor-renderizado
    ports:
      - 3000:3000
    environment: 
      - DOCKER_CONTAINER_EXECUTION=true
      - PORT=3000
      - ALLOWED_IPS=0.0.0.0,:1
      - SHOW_PYTHON_LOGS=true